import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const files = {
  "/index.html": "public/index.html",
  "/app.css": "public/app.css",
  "/app.js": "public/app.js",
  "/input.js": "public/input.js",
  "/stream.js": "public/stream.js",
  "/audio.js": "public/audio.js",
  "/lucide.min.js": "node_modules/lucide/dist/umd/lucide.min.js",
};
const values = await Promise.all(Object.entries(files).map(async ([route, file]) => [route, await readFile(resolve(root, file), "utf8")]));
const output = `// Generated by scripts/generate-assets.mjs.\nexport const assets = ${JSON.stringify(Object.fromEntries(values))};\n`;
await mkdir(resolve(root, "src"), { recursive: true });
await writeFile(resolve(root, "src/generated-assets.js"), output);

const [helper, naudio] = await Promise.all([
  readFile(resolve(root, "vendor/audio/LanBrowser.AudioCapture.exe")),
  readFile(resolve(root, "vendor/audio/NAudio.dll")),
]);
const audioOutput = `// Generated by scripts/generate-assets.mjs.\nexport const audioAssets = ${JSON.stringify({
  helper: helper.toString("base64"),
  naudio: naudio.toString("base64"),
})};\n`;
await writeFile(resolve(root, "src/generated-audio.js"), audioOutput);
